### ISSUE TITLE
∫eˢsin(10s) is not exact

### ISSUE THREAD

**Issue by stevengj** [SciML/SymbolicNumericIntegration.jl#27]
SymbolicNumericIntegration can integrate ∫eˢsin(s) exactly:
```jl
julia> using Symbolics, SymbolicNumericIntegration

julia> @variables s
1-element Vector{Num}:
 s

julia> integrate(exp(s) * sin(s))
((1//2)*exp(s)*sin(s) - (1//2)*cos(s)*exp(s), 0, 0)
```
but for some reason it switches to floating-point approximations if `sin(s)` is changed to `sin(10*s)`:
```jl
julia> integrate(exp(s) * sin(10s))
(0.009900990099009925exp(s)*sin(10s) - 0.09900990099009901exp(s)*cos(10s), 0, 6.878113617473781e-16)
```
even though the exact integral has rational coefficients:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/2913679/198837674-0f7bbe73-47b0-4a48-8932-031f9a04b097.png">

**Comment by B-LIE** [comment]
Similar problem with:
```julia
integrate(1//4*exp(-10t)*sin(t), t)[1]
```
leading to:
<img width="415" alt="image" src="https://github.com/SciML/SymbolicNumericIntegration.jl/assets/54220415/bfcddf84-3dc3-48a8-8451-c41072b4356a">

which also can be made exact if rational numbers are taken advantage of.

Summing terms with rational numbers may easily lead to numerator and denominator larger than what can be handled by Int64, but I don't think that will be common in integrals.

**Comment by shahriariravanian** [comment]
SymbolicNumericIntegration ver 1.2 now supports symbolic integration in many cases. It returns

julia> integrate(1//4*exp(-10t)*sin(t), t; symbolic=true, detailed=false)
(-1//404)*cos(t)*exp(-10t) - (5//202)*sin(t)*exp(-10t)

Symbolic coverage is partial and may still fall back to numerical calculation if necessary.
