### ISSUE TITLE
I cannot it install at all

### ISSUE THREAD

**Issue by lasotek** [SciML/SymbolicNumericIntegration.jl#54]
add SymbolicNumericIntegration
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataDrivenSparse [5b588203]:
 DataDrivenSparse [5b588203] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.2
 └─restricted by compatibility requirements with DataDrivenDiffEq [2445eb08] to versions: uninstalled — no versions left
   └─DataDrivenDiffEq [2445eb08] log:
     ├─possible versions are: 0.1.0-1.2.0 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-1.2.0
     └─restricted by compatibility requirements with SymbolicNumericIntegration [78aadeae] to versions: 0.8.0-0.8.6
       └─SymbolicNumericIntegration [78aadeae] log:
         ├─possible versions are: 0.8.4-1.0.0 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 0.8.4-1.0.0

**Comment by shahriariravanian** [comment]
I just released a new version to the registry. It should work now.
